- hosts: all
  tasks:
    - name: start nginx
      shell: /usr/sbin/nginx
    - name: copy html
      copy:
        src: /home/jenkins/index.html
        dest: /usr/share/nginx/html/index.html
        mode: 0444
