- hosts: all
  tasks:
    - name: install nginx
      yum: name=nginx state=present
      become: yes
    - name: enable nginx
      shell: chkconfig nginx on
      become: yes
    - name: copy html
      copy:
        src: /home/jenkins/index.html
        dest: /usr/share/nginx/html/index.html
        mode: 0444
      become: yes
